Accept it hunti
JuliuszMaretzky/Seed pull request #6
Opened 2018-11-28 20:24 UTC by JuliuszMaretzky

I messed a little in branches, but think it's ok anyway...

2018-11-30 00:20 UTC, huntipl commented
1. give the PR better name expressing what the code is trying to do. You can keep it as the branch name, or call it something like "implemented changes doing xxx"

2018-11-30 00:24 UTC, huntipl requested changes
required changes

2018-11-30 00:24 UTC, huntipl commented on Seed.Tests/PlayerTests.cs
> +            var RestSamples = new List<string>()
restSamples

2018-11-30 00:24 UTC, huntipl commented on Seed/Service.cs
> +                        MoveCharacter((IMove)c);
you're doing double casting here.

```
if(c is IMove move)
{
MoveCharacter(move);
}
```

2018-11-30 00:24 UTC, huntipl commented on Seed/Service.cs
> +                    if (c is IAttack)
same as above

2018-11-30 22:16 UTC, JuliuszMaretzky commented
Required changes commited.

2018-12-01 13:49 UTC, JuliuszMaretzky commented
I added new commits, please look at them.

2018-12-02 14:02 UTC, huntipl commented on Seed.Tests/PlayerTests.cs
> +            var RestSamples = new List<string>()
still capital R

2018-12-02 14:13 UTC, huntipl reviewed
I would do some changes but it's better now so up to you

2018-12-02 14:13 UTC, huntipl commented on Seed/Characters/Player.cs
> +            Console.ForegroundColor = ConsoleColor.White;
why are you setting this to White to change it to grey in a second?

2018-12-02 14:13 UTC, huntipl commented on Seed/Characters/Player.cs
> +            if(character.HP==character.MaxHP)
could be refactored to a method isCharacterFullHP, to contain the logic within the character class

2018-12-02 14:13 UTC, huntipl approved these changes

2018-12-03 21:42 UTC, merged